stages:
  - mirror
  - test
  - stats
  - deploy
  - release

default:
  image: namboy94/ci-docker-environment:0.9.0
  before_script:
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa

github_mirror:
  stage: mirror
  tags: [docker]
  only: [master, develop]
  before_script:
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git-mirror-pusher git@github.com:namboy94/betbot.git
      master develop

stylecheck:
  stage: test
  tags: [docker]
  script:
    - python-codestyle-check

unittest:
  stage: test
  tags: [docker]
  only: [master, develop]
  script:
    - pip install tensorflow
    - python-unittest

type_check:
  stage: test
  tags: [docker]
  script:
    - python-static-type-check

gitstats:
  stage: stats
  tags: [docker]
  script:
    - gitstats-gen

docgen:
  stage: stats
  tags: [docker]
  script:
    - pip install tensorflow
    - sphinx-docgen

deploy_app:
  stage: deploy
  tags: [privileged]
  only: [master]
  before_script: []
  script:
    - echo "$ENV_FILE" > .env
    - docker-compose build
    - docker-compose up -d
    - rm .env

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"

pypi_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - pypi-upload
